import { Fragrance } from "./types";

export const mockFragrances: Fragrance[] = [
  {
    id: 1,
    name: "Bleu de Chanel",
    brand: "Chanel",
    year: 2010,
    gender: "Male",
    description: "An aromatic-woody fragrance that opens with fresh citrus and mint notes, evolving into a sophisticated blend of ginger, nutmeg, and jasmine, before settling into a warm base of incense, vetiver, and cedar.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Bleu+de+Chanel",
    topNotes: ["Lemon", "Mint", "Pink Pepper"],
    middleNotes: ["Ginger", "Nutmeg", "Jasmine"],
    baseNotes: ["Incense", "Vetiver", "Cedar"],
    longevity: 8,
    sillage: 7,
    season: ["Fall", "Winter", "Spring"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 2,
    name: "Sauvage",
    brand: "Dior",
    year: 2015,
    gender: "Male",
    description: "A fresh and spicy fragrance with a powerful opening of Calabrian bergamot and pepper, leading to a heart of Sichuan pepper and lavender, finished with ambroxan and patchouli.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Sauvage",
    topNotes: ["Calabrian Bergamot", "Pepper"],
    middleNotes: ["Sichuan Pepper", "Lavender", "Pink Pepper"],
    baseNotes: ["Ambroxan", "Patchouli", "Labdanum"],
    longevity: 9,
    sillage: 8,
    season: ["Spring", "Summer", "Fall"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 3,
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    year: 2014,
    gender: "Female",
    description: "A gourmand floral fragrance with an addictive blend of coffee, vanilla, and white flowers. A modern and mysterious scent that captivates the senses.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Black+Opium",
    topNotes: ["Pink Pepper", "Orange Blossom", "Pear"],
    middleNotes: ["Coffee", "Jasmine", "Bitter Almond"],
    baseNotes: ["Vanilla", "Patchouli", "Cedar"],
    longevity: 8,
    sillage: 7,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 4,
    name: "Oud Wood",
    brand: "Tom Ford",
    year: 2007,
    gender: "Unisex",
    description: "A luxurious woody fragrance featuring rare oud wood, sandalwood, and rosewood, blended with exotic spices and vanilla. Rich, warm, and sophisticated.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Oud+Wood",
    topNotes: ["Cardamom", "Pink Pepper", "Chinese Pepper"],
    middleNotes: ["Oud Wood", "Rosewood", "Sandalwood"],
    baseNotes: ["Tonka Bean", "Vanilla", "Amber"],
    longevity: 10,
    sillage: 6,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 5,
    name: "Replica: By the Fireplace",
    brand: "Maison Margiela",
    year: 2015,
    gender: "Unisex",
    description: "A cozy, warm fragrance that captures the essence of a crackling fireplace. Notes of chestnut, vanilla, and cashmere wood create an intimate, comforting atmosphere.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Bleu+de+Chanel",
    topNotes: ["Pink Pepper", "Orange Blossom", "Clove Oil"],
    middleNotes: ["Chestnut", "Guaiac Wood", "Cashmeran"],
    baseNotes: ["Vanilla", "Chestnut", "Vetiver"],
    longevity: 7,
    sillage: 5,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 6,
    name: "La Vie Est Belle",
    brand: "Lancôme",
    year: 2012,
    gender: "Female",
    description: "A gourmand floral fragrance celebrating happiness and beauty. A sweet and joyful blend of iris, patchouli, and praline that radiates positivity.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=La+Vie+Est+Belle",
    topNotes: ["Blackcurrant", "Pear"],
    middleNotes: ["Iris", "Jasmine", "Orange Blossom"],
    baseNotes: ["Praline", "Patchouli", "Vanilla"],
    longevity: 8,
    sillage: 7,
    season: ["Spring", "Summer", "Fall"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 7,
    name: "Acqua di Gio",
    brand: "Giorgio Armani",
    year: 1996,
    gender: "Male",
    description: "A fresh aquatic fragrance inspired by the Mediterranean. Bright citrus and marine notes blend with aromatic herbs and woody accords.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Acqua+di+Gio",
    topNotes: ["Lemon", "Mandarin Orange", "Marine Notes"],
    middleNotes: ["Jasmine", "Calone", "Neroli", "Rosemary"],
    baseNotes: ["Amberwood", "Patchouli", "White Musk"],
    longevity: 6,
    sillage: 5,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day"],
    userRating: null,
    shelf: null,
  },
  {
    id: 8,
    name: "Flowerbomb",
    brand: "Viktor & Rolf",
    year: 2005,
    gender: "Female",
    description: "An explosive floral fragrance that bursts with jasmine, rose, and orchid. A modern, opulent scent that celebrates femininity.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Flowerbomb",
    topNotes: ["Bergamot", "Tea"],
    middleNotes: ["Jasmine", "Rose", "Orchid"],
    baseNotes: ["Patchouli", "Vanilla", "Amber"],
    longevity: 8,
    sillage: 8,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 9,
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    year: 2007,
    gender: "Unisex",
    description: "A rich, opulent fragrance featuring tobacco leaf, vanilla, and dried fruits. Warm, sweet, and luxurious with a hint of spice.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Bleu+de+Chanel",
    topNotes: ["Tobacco Leaf", "Spice Notes"],
    middleNotes: ["Tonka Bean", "Tobacco Flower", "Vanilla"],
    baseNotes: ["Dried Fruits", "Honey", "Cocoa"],
    longevity: 10,
    sillage: 7,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 10,
    name: "Good Girl",
    brand: "Carolina Herrera",
    year: 2016,
    gender: "Female",
    description: "A seductive floral gourmand that contrasts light and dark. Tuberose and jasmine meet almond and cocoa for a mysterious, alluring scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Good+Girl",
    topNotes: ["Almond", "Coffee"],
    middleNotes: ["Tuberose", "Jasmine", "Tuberose"],
    baseNotes: ["Cocoa", "Tonka Bean", "Sandalwood"],
    longevity: 8,
    sillage: 7,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 11,
    name: "Aventus",
    brand: "Creed",
    year: 2010,
    gender: "Male",
    description: "A fruity chypre fragrance inspired by the dramatic life of a historic emperor. Pineapple, blackcurrant, and birch create a bold, sophisticated scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Aventus",
    topNotes: ["Pineapple", "Bergamot", "Blackcurrant", "Apple"],
    middleNotes: ["Birch", "Patchouli", "Jasmine", "Rose"],
    baseNotes: ["Musk", "Oakmoss", "Ambergris", "Vanilla"],
    longevity: 9,
    sillage: 8,
    season: ["Spring", "Summer", "Fall"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 12,
    name: "Coco Mademoiselle",
    brand: "Chanel",
    year: 2001,
    gender: "Female",
    description: "A modern, fresh oriental fragrance. Bright citrus and rose open to a heart of jasmine and patchouli, finished with vetiver and vanilla.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Coco+Mademoiselle",
    topNotes: ["Orange", "Mandarin Orange", "Orange Blossom"],
    middleNotes: ["Turkish Rose", "Jasmine", "Mimosa"],
    baseNotes: ["Patchouli", "Vetiver", "Vanilla", "White Musk"],
    longevity: 8,
    sillage: 7,
    season: ["Spring", "Summer", "Fall"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 13,
    name: "The One",
    brand: "Dolce & Gabbana",
    year: 2006,
    gender: "Female",
    description: "A warm, sensual oriental fragrance. Peach and lychee open to a floral heart of lily and jasmine, resting on a base of vanilla and amber.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=The+One",
    topNotes: ["Peach", "Lychee", "Bergamot"],
    middleNotes: ["Lily", "Jasmine", "Plum"],
    baseNotes: ["Vanilla", "Amber", "Musk"],
    longevity: 7,
    sillage: 6,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 14,
    name: "Eros",
    brand: "Versace",
    year: 2012,
    gender: "Male",
    description: "A fresh, aromatic fragrance with a modern twist. Mint, green apple, and lemon open to tonka bean and vanilla, finished with vetiver and cedarwood.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Eros",
    topNotes: ["Mint", "Green Apple", "Lemon"],
    middleNotes: ["Tonka Bean", "Ambroxan", "Geranium"],
    baseNotes: ["Vanilla", "Vetiver", "Cedarwood", "Oakmoss"],
    longevity: 8,
    sillage: 7,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 15,
    name: "Replica: Jazz Club",
    brand: "Maison Margiela",
    year: 2013,
    gender: "Unisex",
    description: "A warm, boozy fragrance that captures the atmosphere of a 1950s jazz club. Rum, tobacco, and vanilla create a sophisticated, intimate scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Replica+Jazz+Club",
    topNotes: ["Pink Pepper", "Lemon", "Neroli"],
    middleNotes: ["Rum", "Clary Sage", "Java Vetiver"],
    baseNotes: ["Tobacco Leaf", "Vanilla", "Styrax"],
    longevity: 8,
    sillage: 6,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 16,
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    year: 2001,
    gender: "Female",
    description: "A fresh, aquatic fragrance inspired by the Mediterranean. Sicilian lemon, apple, and cedarwood create a bright, uplifting scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Light+Blue",
    topNotes: ["Sicilian Lemon", "Apple", "Cedarwood"],
    middleNotes: ["Bamboo", "Jasmine", "White Rose"],
    baseNotes: ["Amber", "Cedarwood", "Musk"],
    longevity: 6,
    sillage: 5,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day"],
    userRating: null,
    shelf: null,
  },
  {
    id: 17,
    name: "Spicebomb",
    brand: "Viktor & Rolf",
    year: 2012,
    gender: "Male",
    description: "An explosive spicy fragrance. Saffron, pink pepper, and bergamot open to cinnamon and paprika, finished with leather and tobacco.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Spicebomb",
    topNotes: ["Bergamot", "Grapefruit", "Pink Pepper"],
    middleNotes: ["Saffron", "Cinnamon", "Paprika"],
    baseNotes: ["Leather", "Tobacco", "Vetiver"],
    longevity: 9,
    sillage: 8,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 18,
    name: "Alien",
    brand: "Thierry Mugler",
    year: 2005,
    gender: "Female",
    description: "A mysterious, woody floral fragrance. Jasmine sambac takes center stage, supported by cashmeran and white amber for an otherworldly scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Alien",
    topNotes: ["Jasmine Sambac"],
    middleNotes: ["Cashmeran"],
    baseNotes: ["White Amber", "Woody Notes"],
    longevity: 9,
    sillage: 8,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 19,
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    year: 2015,
    gender: "Unisex",
    description: "An airy, floral-woody fragrance. Saffron and ambergris create a unique, luxurious scent that is both warm and ethereal.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Baccarat+Rouge+540",
    topNotes: ["Saffron", "Jasmine"],
    middleNotes: ["Amberwood", "Ambergris"],
    baseNotes: ["Fir Resin", "Cedar"],
    longevity: 10,
    sillage: 7,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 20,
    name: "One Million",
    brand: "Paco Rabanne",
    year: 2008,
    gender: "Male",
    description: "A fresh spicy fragrance with a modern twist. Blood mandarin, mint, and rose open to cinnamon and spice, finished with leather and amber.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=One+Million",
    topNotes: ["Blood Mandarin", "Mint", "Grapefruit"],
    middleNotes: ["Rose", "Cinnamon", "Spice Notes"],
    baseNotes: ["Leather", "Amber", "White Woods"],
    longevity: 8,
    sillage: 7,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 21,
    name: "J'adore",
    brand: "Dior",
    year: 1999,
    gender: "Female",
    description: "A floral fragrance celebrating femininity. Ylang-ylang, damascus rose, and jasmine create an elegant, timeless scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Bleu+de+Chanel",
    topNotes: ["Ylang-Ylang", "Bergamot", "Pear"],
    middleNotes: ["Damascus Rose", "Orchid", "Freesia"],
    baseNotes: ["Jasmine", "Amaranth", "Vanilla"],
    longevity: 7,
    sillage: 6,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 22,
    name: "Replica: Beach Walk",
    brand: "Maison Margiela",
    year: 2012,
    gender: "Unisex",
    description: "A fresh, sunny fragrance that captures the essence of a beach day. Bergamot, pink pepper, and coconut create a carefree, summery scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Replica+Beach+Walk",
    topNotes: ["Bergamot", "Pink Pepper", "Lemon"],
    middleNotes: ["Ylang-Ylang", "Coconut", "Heliotrope"],
    baseNotes: ["Musk", "Benzoin", "Cedarwood"],
    longevity: 6,
    sillage: 5,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day"],
    userRating: null,
    shelf: null,
  },
  {
    id: 23,
    name: "The One for Men",
    brand: "Dolce & Gabbana",
    year: 2008,
    gender: "Male",
    description: "A warm, spicy oriental fragrance. Grapefruit and coriander open to cardamom and ginger, finished with amber and tobacco.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Bleu+de+Chanel",
    topNotes: ["Grapefruit", "Coriander", "Basil"],
    middleNotes: ["Cardamom", "Ginger"],
    baseNotes: ["Amber", "Tobacco"],
    longevity: 7,
    sillage: 6,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 24,
    name: "Angel",
    brand: "Thierry Mugler",
    year: 1992,
    gender: "Female",
    description: "A revolutionary gourmand fragrance. Chocolate, vanilla, and patchouli create a unique, addictive scent that defies categorization.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Angel",
    topNotes: ["Bergamot", "Melon", "Mandarin Orange"],
    middleNotes: ["Red Berries", "Jasmine", "Honey"],
    baseNotes: ["Patchouli", "Chocolate", "Vanilla", "Caramel"],
    longevity: 10,
    sillage: 9,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
  {
    id: 25,
    name: "Acqua di Gioia",
    brand: "Giorgio Armani",
    year: 2010,
    gender: "Female",
    description: "A fresh, aquatic fragrance for women. Lemon, mint, and brown sugar open to jasmine and peony, finished with cedar and labdanum.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Bleu+de+Chanel",
    topNotes: ["Lemon", "Mint", "Brown Sugar"],
    middleNotes: ["Jasmine", "Peony", "Water Notes"],
    baseNotes: ["Cedar", "Labdanum", "Pink Pepper"],
    longevity: 6,
    sillage: 5,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day"],
    userRating: null,
    shelf: null,
  },
  {
    id: 26,
    name: "Fahrenheit",
    brand: "Dior",
    year: 1988,
    gender: "Male",
    description: "A unique, unconventional fragrance. Violet leaf, nutmeg, and leather create a distinctive, memorable scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Fahrenheit",
    topNotes: ["Lavender", "Mandarin Orange", "Bergamot", "Lemon"],
    middleNotes: ["Violet Leaf", "Nutmeg", "Hawthorn", "Jasmine"],
    baseNotes: ["Leather", "Patchouli", "Amber", "Tonka Bean"],
    longevity: 8,
    sillage: 7,
    season: ["Fall", "Winter"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 27,
    name: "Chance",
    brand: "Chanel",
    year: 2002,
    gender: "Female",
    description: "A fresh, floral fragrance celebrating chance encounters. Pink pepper, jasmine, and patchouli create an optimistic, modern scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Chance",
    topNotes: ["Pink Pepper", "Hyacinth", "Pineapple"],
    middleNotes: ["Jasmine", "Rose", "Tea Rose"],
    baseNotes: ["Patchouli", "Vetiver", "Amber", "White Musk"],
    longevity: 7,
    sillage: 6,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 28,
    name: "Replica: Lazy Sunday Morning",
    brand: "Maison Margiela",
    year: 2013,
    gender: "Unisex",
    description: "A soft, clean fragrance that captures the feeling of a lazy Sunday morning. Aldehydes, pear, and lily of the valley create a fresh, comforting scent.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Replica+Lazy+Sunday+Morning",
    topNotes: ["Aldehydes", "Pear", "Bergamot"],
    middleNotes: ["Lily of the Valley", "Rose", "Orange Blossom"],
    baseNotes: ["Musk", "White Woods", "Iris"],
    longevity: 6,
    sillage: 4,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day"],
    userRating: null,
    shelf: null,
  },
  {
    id: 29,
    name: "Invictus",
    brand: "Paco Rabanne",
    year: 2013,
    gender: "Male",
    description: "A fresh, marine fragrance with a modern twist. Grapefruit, mandarin, and bay leaf open to jasmine and pink pepper, finished with guaiac wood and ambergris.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Invictus",
    topNotes: ["Grapefruit", "Mandarin Orange", "Marine Notes"],
    middleNotes: ["Bay Leaf", "Jasmine", "Pink Pepper"],
    baseNotes: ["Guaiac Wood", "Ambergris", "Oakmoss"],
    longevity: 7,
    sillage: 6,
    season: ["Spring", "Summer"],
    timeOfDay: ["Day", "Evening"],
    userRating: null,
    shelf: null,
  },
  {
    id: 30,
    name: "Shalimar",
    brand: "Guerlain",
    year: 1925,
    gender: "Female",
    description: "An iconic oriental fragrance. Bergamot, iris, and vanilla create a timeless, luxurious scent that has captivated for nearly a century.",
    image: "https://placehold.co/400x500/141414/ff6b35?text=Shalimar",
    topNotes: ["Bergamot", "Lemon", "Citrus Notes"],
    middleNotes: ["Iris", "Jasmine", "Rose", "Patchouli"],
    baseNotes: ["Vanilla", "Tonka Bean", "Benzoin", "Opoponax"],
    longevity: 9,
    sillage: 8,
    season: ["Fall", "Winter"],
    timeOfDay: ["Evening", "Night"],
    userRating: null,
    shelf: null,
  },
];
